//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JuniperTaxApp.Core.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("JuniperTaxApp.Core.Resources.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string OrderDetailsTitle {
            get {
                return ResourceManager.GetString("OrderDetailsTitle", resourceCulture);
            }
        }
        
        internal static string CalculatedTaxTitle {
            get {
                return ResourceManager.GetString("CalculatedTaxTitle", resourceCulture);
            }
        }
        
        internal static string CalculateButton {
            get {
                return ResourceManager.GetString("CalculateButton", resourceCulture);
            }
        }
        
        internal static string GettingStarted {
            get {
                return ResourceManager.GetString("GettingStarted", resourceCulture);
            }
        }
        
        internal static string OriginZipCode {
            get {
                return ResourceManager.GetString("OriginZipCode", resourceCulture);
            }
        }
        
        internal static string DestinationZipCode {
            get {
                return ResourceManager.GetString("DestinationZipCode", resourceCulture);
            }
        }
        
        internal static string ZipCodeHint {
            get {
                return ResourceManager.GetString("ZipCodeHint", resourceCulture);
            }
        }
        
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        internal static string OriginState {
            get {
                return ResourceManager.GetString("OriginState", resourceCulture);
            }
        }
        
        internal static string DestinationState {
            get {
                return ResourceManager.GetString("DestinationState", resourceCulture);
            }
        }
        
        internal static string OrderAmount {
            get {
                return ResourceManager.GetString("OrderAmount", resourceCulture);
            }
        }
        
        internal static string OrderAmountHint {
            get {
                return ResourceManager.GetString("OrderAmountHint", resourceCulture);
            }
        }
        
        internal static string ShippingAmount {
            get {
                return ResourceManager.GetString("ShippingAmount", resourceCulture);
            }
        }
        
        internal static string ShippingAmountHint {
            get {
                return ResourceManager.GetString("ShippingAmountHint", resourceCulture);
            }
        }
        
        internal static string CityRate {
            get {
                return ResourceManager.GetString("CityRate", resourceCulture);
            }
        }
        
        internal static string CombinedDistrictRate {
            get {
                return ResourceManager.GetString("CombinedDistrictRate", resourceCulture);
            }
        }
        
        internal static string CombinedRate {
            get {
                return ResourceManager.GetString("CombinedRate", resourceCulture);
            }
        }
        
        internal static string CountryRate {
            get {
                return ResourceManager.GetString("CountryRate", resourceCulture);
            }
        }
        
        internal static string CountyRate {
            get {
                return ResourceManager.GetString("CountyRate", resourceCulture);
            }
        }
        
        internal static string StateRate {
            get {
                return ResourceManager.GetString("StateRate", resourceCulture);
            }
        }
        
        internal static string TaxesDue {
            get {
                return ResourceManager.GetString("TaxesDue", resourceCulture);
            }
        }
    }
}
